### ISSUE TITLE
RPP 01 - Etherscan Plugin - Migration

### ISSUE THREAD

**Issue by defiboy** [Machinalabs/remix-plugin-proposals#1]
#### Background

The current Remix Etherscan Plugin is located at: 

https://github.com/Machinalabs/remix-etherscan

And hosted in surge http://machinalabs-remix-etherscan-plugin.surge.sh/.
 
#### Proposal

- Migrate existing codebase to a React based application.

- Modify the UI interface.

    - Split the API key capture step from the main plugin functionality.

    - Include a ‘settings’ icon to allow users to edit the Etherscan API key.

    - Include an autocomplete to the ‘Contract Name’ input text. 

    - Allow users to lookup GUID receipts (Guid retrieved when we perform a contract verification)

#### Split views

The following image shows the dedicated API key capture view.

<img width="892" alt="Screenshot 2020-04-30 at 20 41 21" src="https://user-images.githubusercontent.com/56453782/80753064-8aae8c80-8b24-11ea-861d-feda8cab3746.png">

The following image shows the new Contract Verification view with a new settings and receipts options.

![verification-view](https://user-images.githubusercontent.com/56453782/81534758-78bcbd00-9360-11ea-9cb0-097758d0966e.png)

The receipts view

![receipts-view](https://user-images.githubusercontent.com/56453782/81534744-735f7280-9360-11ea-8273-c3e1da2a1d76.png)

#### Remix Requirements

Remix should allow plugins to get a list of all of the contract names in the existing editor.

#### Resources

https://etherscan.io/sourcecode-demo.html

**Comment by yann300** [comment]
> Remix should allow plugins to get a list of all of the contract names in the existing editor.

you can get that from the compilation result right?

**Comment by defiboy** [comment]
Plugin migrated and deployed to https://machinalabs-remix-etherscan-plugin-v2.surge.sh
