### ISSUE TITLE
RPP 03 - Gas Profiler v2

### ISSUE THREAD

**Issue by defiboy** [Machinalabs/remix-plugin-proposals#3]
#### Background

The current Remix Gas Profiler Plugin is located at: 

https://github.com/Machinalabs/remix-gas-profiler

And hosted in surge https://remix-gas-profiler.surge.sh
 
Some limitations of the plugin are:

- It only work with 1 file contracts
- It wasn't tested in cases where we have internal contract calls
- Gas costs are not fully accurate
- Poor UX (source code is rendered, however adding annotations + source highlighting would improve the plugin usability)

#### Proposal

- Add annotation and source highlighting for the gas profiler plugin, i.e highlight the line that consume the most gas.

- Add gas costs in the gutter

- Improve test cases

    - Support multiple files

    - Support internal calls

    - Improve gas calculation

#### Remix Requirements

Allow plugins to highlight more than one item at a time

#### Resources

Editor API https://github.com/ethereum/remix-plugins-directory/blob/master/common-api/editor/api.ts

**Comment by yann300** [comment]
> Allow plugins to highlight more than one item at a time

this part is already deployed to remix-alpha, and with this new function https://github.com/ethereum/remix-plugins-directory/blob/master/common-api/editor/api.ts#L12
