### ISSUE TITLE
RPP 04 - Sol2UML

### ISSUE THREAD

**Issue by EdsonAlcala** [Machinalabs/remix-plugin-proposals#4]
#### Background

UML diagrams are visual representations of a system, it helps to better understand its functionality and component's relationship.

There is [previous](https://github.com/naddison36/sol2uml) work to generate UML diagrams from Solidity and it was integrated into Etherscan (see image below)

<img width="847" alt="Screenshot 2020-05-11 at 21 07 56" src="https://user-images.githubusercontent.com/3077635/81606780-8bb8a700-93cb-11ea-92e7-e1fe83557075.png">

Image source: https://etherscan.io/viewsvg?t=1&a=0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359

#### Proposal

- Create a Solidity to UML Remix plugin that generates UML diagrams of the compiled contract.

#### Design

![remix-solidity-2-uml](https://user-images.githubusercontent.com/3077635/81609024-1058f480-93cf-11ea-8d82-a03f015e832e.png)

_Note: The UML diagram style could change due to sol2UML dependencies compatibility in the browser._

#### Resources / References

[Sol2UML] (https://github.com/naddison36/sol2uml)
[Solidity-parser-antlr] (https://github.com/ConsenSys/solidity-parser-antlr)

**Comment by LianaHus** [comment]
IMHO there should be a way to export this to be able to share. @EdsonAlcala Do you have any suggestions for that?

**Comment by EdsonAlcala** [comment]
that would be very cool, maybe some way to export to pdf? or image? Or maybe a shareable link? For instance this one http://www.nomnoml.com/ it is like a viewer, you can paste code and view the diagram
